### ISSUE TITLE
It doesn't seem to work

### ISSUE THREAD

**Issue by ooker777** [carloblasi/vscode-search-long-paths#1]
Is this supposed to work right in the native find and replace feature of vscode, or does it have a different UI?

**Comment by carloblasi** [comment]
You should see a new icon in the activity bar. The extension has its own UI, which is almost identical to the native find and replace. 

![image](https://user-images.githubusercontent.com/8105766/216279452-b7714ba2-9386-491c-a16c-ef1113a3ad5b.png)

**Comment by carloblasi** [comment]
Added "how to use" paragraph to the readme file, thank you
